import { identities, actions, variants, simulate, sanitizeAttempts, reviewAttempts, authorizationReport } from './authorization-model.js?v=20261005-reviews1';

export function mountAuthorizationLab(root, { owner, language }) {
  if (!root || !owner) return;
  const tr = (ar, en) => language === 'ar' ? ar : en;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
  const key = `biuret-authorization-practice-v1:${owner}`;
  let state; try { state = JSON.parse(localStorage.getItem(key)); } catch {}
  if (!state || typeof state !== 'object' || Array.isArray(state)) state = {};
  state.attempts = sanitizeAttempts(state.attempts);
  state.reasoning = typeof state.reasoning === 'string' ? state.reasoning.slice(0,4000) : '';
  const version = { original: tr('قبل الإصلاح', 'Before repair'), partial: tr('إصلاح جزئي', 'Partial repair'), fixed: tr('إصلاح جميع المسارات', 'All routes repaired') };
  const action = { read: tr('قراءة', 'Read'), export: tr('تصدير', 'Export'), update: tr('تعديل', 'Update') };
  const identity = { guest: tr('زائر بلا جلسة', 'Guest without a session'), 'viewer-A': tr('قارئ في A', 'Viewer in A'), 'editor-A': tr('محرر في A', 'Editor in A'), 'viewer-B': tr('قارئ في B', 'Viewer in B') };
  const options = (items, labels) => items.map(v => `<option value="${v}">${esc(labels[v] || v)}</option>`).join('');
  root.innerHTML = `<section class="evidence-workbench authorization-workbench" dir="${language === 'ar' ? 'rtl' : 'ltr'}">
    <div class="workbench-heading"><span class="section-kicker">${tr('اختبار الاختراق / أمن التطبيقات', 'PENTEST / APPLICATION SECURITY')}</span><h2>${tr('هل الإصلاح كامل أم يحمي مساراً واحداً؟', 'Is the repair complete, or protecting just one route?')}</h2><p>${tr('افحص API صناعية للتقارير. توقّع قرار السياسة قبل تشغيل كل حالة، ثم قارنه بالاستجابة. جرّب حسابين وفعلاً مسموحاً وآخر ممنوعاً؛ رمز الحالة وحده ليس التقرير.', 'Inspect a synthetic reports API. Predict the policy decision before running each case, then compare it with the response. Test two accounts and allowed and denied actions; a status code alone is not a report.')}</p></div>
    <div class="authorization-policy"><h3>${tr('السياسة المطلوبة', 'Required policy')}</h3><ul><li>${tr('لا وصول دون جلسة مصادقة.', 'No access without an authenticated session.')}</li><li>${tr('A يصل إلى سجلات A فقط، وB إلى B فقط.', 'A accesses only A records; B accesses only B records.')}</li><li>${tr('القارئ يقرأ ويصدّر، والمحرر يستطيع التعديل أيضاً ضمن مستأجره.', 'Viewers read and export; editors also update within their tenant.')}</li><li>${tr('الرفض لا يحتوي بيانات السجل في جسم الاستجابة.', 'Denied responses contain no report data.')}</li></ul><p class="library-note">${tr('محاكاة محلية ببيانات صناعية؛ لا تتصل بخوادم ولا تمنح XP أو شهادة. «الإصلاح» هنا نسخة من النموذج التعليمي فقط.', 'Local synthetic simulation; no server requests, XP or certificates. A repair here is a version of this teaching model only.')}</p></div>
    <form data-access-case class="authorization-case"><label>${tr('نسخة التطبيق', 'Application version')}<select name="variant">${options(variants,version)}</select></label><label>${tr('هوية الطالب', 'Caller identity')}<select name="identity">${options(Object.keys(identities),identity)}</select></label><label>${tr('مستأجر السجل', 'Record tenant')}<select name="object">${options(['A','B'],{})}</select></label><label>${tr('الفعل', 'Action')}<select name="action">${options(actions,action)}</select></label><label>${tr('توقعك وفق السياسة', 'Your policy prediction')}<select name="prediction" required><option value="">${tr('اختر قبل التجربة', 'Choose before running')}</option><option value="allow">${tr('مسموح', 'Allowed')}</option><option value="deny">${tr('مرفوض', 'Denied')}</option></select></label><button class="button button-primary" type="submit">${tr('نفّذ الحالة الصناعية', 'Run synthetic case')}</button></form>
    <div data-observation class="authorization-observation" role="status" tabindex="-1"></div>
    <div class="workbench-table-scroll"><table><caption>${tr('مصفوفة الاختبارات — النسخة المختارة', 'Test matrix — selected version')}</caption><thead><tr><th>${tr('الهوية / السجل', 'Identity / record')}</th><th>${tr('الفعل', 'Action')}</th><th>${tr('توقعك', 'Prediction')}</th><th>${tr('الاستجابة', 'Response')}</th><th>${tr('مطابقة السياسة', 'Policy match')}</th></tr></thead><tbody data-access-rows></tbody></table></div>
    <p data-coverage role="status"></p><button data-review type="button" class="button button-outline">${tr('راجع التغطية والإصلاح', 'Review coverage and repair')}</button><div data-access-review role="status" tabindex="-1"></div>
    <label class="authorization-report">${tr('اكتب تقريرك: حالة تجاوز، حالة مسموحة، نطاق الإصلاح وحدود الدليل', 'Write your report: bypass, allowed control, repair scope and evidence limits')}<textarea data-reasoning rows="5" maxlength="4000">${esc(state.reasoning)}</textarea></label><p class="library-note">${tr('النص الحر لا يُقيّم آلياً. راجع هوية الحالة ومسارها والنتيجة قبل وبعد، ولا تضع بيانات شخصية. ملاحظاتك تبقى لهذا الحساب في هذا المتصفح.', 'Written reasoning is not automatically graded. Check identity, route and before/after results; omit personal data. Notes stay with this account in this browser.')}</p><div class="workbench-actions"><button data-access-export type="button" class="button button-outline">${tr('تنزيل تقرير الاختبارات', 'Download test report')}</button><small data-access-save>${tr('جاهز للتدريب', 'Ready to practice')}</small></div>
  </section>`;
  const form = root.querySelector('[data-access-case]');
  if (variants.includes(state.variant)) form.elements.variant.value = state.variant;
  const save = () => { state.variant=form.elements.variant.value; try { localStorage.setItem(key,JSON.stringify({variant:state.variant, attempts:state.attempts, reasoning:state.reasoning})); root.querySelector('[data-access-save]').textContent=tr('محفوظ في هذا المتصفح','Saved in this browser'); } catch { root.querySelector('[data-access-save]').textContent=tr('تعذر الحفظ؛ نزّل التقرير قبل المغادرة.','Could not save; download your report before leaving.'); } };
  const render = () => {
    const v=form.elements.variant.value, rows=state.attempts.filter(c=>c.variant===v);
    root.querySelector('[data-access-rows]').innerHTML=rows.length ? rows.map(c=>{const r=simulate(c); return `<tr><td>${esc(identity[c.identity])} / <bdi>${c.object}</bdi></td><td>${action[c.action]}</td><td>${c.prediction==='allow'?tr('مسموح','Allowed'):tr('مرفوض','Denied')}</td><td dir="ltr">${r.status} · ${esc(r.body || 'empty')}</td><td>${r.compliant?tr('مطابق','Matches'):tr('تجاوز للسياسة','Policy bypass')}</td></tr>`;}).join('') : `<tr><td colspan="5">${tr('لا حالات بعد. ابدأ بحالة مسموحة ثم اختبار رفض.', 'No cases yet. Start with an allowed control, then a denial test.')}</td></tr>`;
    root.querySelector('[data-coverage]').textContent=tr(`${rows.length} / 24 حالة مختلفة في هذه النسخة. إعادة الحالة تحدّث صفها.`,`${rows.length} / 24 distinct cases for this version. Repeating a case updates its row.`);
    root.querySelector('[data-access-review]').replaceChildren();
  };
  render();
  form.addEventListener('submit',e=>{e.preventDefault();const c=Object.fromEntries(new FormData(form));state.attempts=sanitizeAttempts([...state.attempts,c]);const r=simulate(c);render();const out=root.querySelector('[data-observation]');out.innerHTML=`<h3>${tr('نتيجة الحالة','Case observation')}</h3><p dir="ltr">${r.status} · ${esc(r.body || 'empty')}</p><p>${(c.prediction==='allow')===r.expected?tr('توقعك يطابق السياسة.','Your prediction matches the policy.'):tr('راجع توقعك: الملكية والفعل والجلسة شروط منفصلة.','Recheck your prediction: ownership, action and session are separate requirements.')}</p><p>${r.compliant?tr('هذه الحالة تطابق السياسة؛ اختبر بقية الحالات قبل الحكم على الإصلاح.','This case matches policy; test the remaining cases before judging the repair.'):tr('وجدت تجاوزاً: الوصول الفعلي أوسع مما تسمح به السياسة. وثّق الهوية والسجل والفعل.','A bypass: observed access exceeds policy. Record identity, object and action.')}</p>`;out.focus();save();});
  form.elements.variant.addEventListener('change',()=>{root.querySelector('[data-observation]').replaceChildren();form.elements.prediction.value='';render();save();});
  root.querySelector('[data-reasoning]').addEventListener('input',e=>{state.reasoning=e.target.value;save();});
  root.querySelector('[data-review]').addEventListener('click',()=>{const r=reviewAttempts(state.attempts,form.elements.variant.value);const out=root.querySelector('[data-access-review]');out.innerHTML=`<h3>${tr('مراجعة التغطية','Coverage review')}</h3><p>${tr(`${r.predictions}/${r.tested} توقعات صحيحة · ${r.findings} حالات تجاوز`,`${r.predictions}/${r.tested} correct predictions · ${r.findings} bypass cases`)}</p><p>${r.outcome==='finding'?tr('الإصلاح لا يطابق السياسة في كل الحالات المجربة. قارِن المسارات قبل وبعد وحدد ما بقي مفتوحاً.','The repair does not match policy in all tested cases. Compare routes before/after and identify what remains open.'):r.outcome==='covered'?tr('اختبرت الحالات الأربع والعشرين دون تجاوز في هذا النموذج. هذا لا يثبت أمان تطبيق حقيقي أو كل وظائفه.','All 24 cases match policy in this model. This does not establish the security of a real application or all its functions.'):tr('التغطية ناقصة؛ لا تحكم بأن الإصلاح مكتمل. اختبر هويات وأفعالاً وسجلات أخرى مع حالة مسموحة.','Coverage is incomplete; do not call the repair complete. Test remaining identities, actions and objects, including an allowed control.')}</p>`;out.focus();});
  root.querySelector('[data-access-export]').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(authorizationReport(state,language),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='biuret-authorization-practice.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
}
