import { courses, lessonById, localized } from './learning-content.js?v=20261006-free1';
import { labs } from './labs.js?v=20261006-free1';
import { currentLanguage } from './i18n.js?v=20261006-free1';

const root = document.querySelector('#catalog-main');
const page = document.querySelector('.site-shell')?.dataset.page;
const l = (value) => localized(value, currentLanguage());
const tr = (ar, en) => currentLanguage() === 'en' ? en : ar;
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[char]);

const toolGuides = [
  { tag: 'BROWSER', title: { ar: 'أدوات المطوّر في المتصفح', en: 'Browser DevTools' }, purpose: { ar: 'اقرأ الطلب والاستجابة والترويسات في تبويب Network قبل تفسير سلوك الصفحة.', en: 'Inspect requests, responses and headers in Network before interpreting page behavior.' }, steps: [{ ar: 'افتح صفحة تدريب تملكها، ثم تبويب Network.', en: 'Open a training page you control, then the Network tab.' }, { ar: 'أعد تحميل الصفحة واختر طلباً واحداً.', en: 'Reload and select one request.' }, { ar: 'قارن العنوان والطريقة ورمز الحالة والترويسات.', en: 'Compare URL, method, status and headers.' }], example: 'GET /training/profile → 200 OK', href: 'lab.html?id=http-basics' },
  { tag: 'LINUX', title: { ar: 'قراءة أذونات Linux', en: 'Read Linux permissions' }, purpose: { ar: 'فسّر مخرجات ls -l وحدد من يستطيع قراءة الملف أو تعديله.', en: 'Interpret ls -l output and identify who can read or change a file.' }, steps: [{ ar: 'اقرأ مجموعات المالك والمجموعة والآخرين.', en: 'Read the owner, group and others permission groups.' }, { ar: 'حوّل r وw وx إلى 4 و2 و1 لكل مجموعة.', en: 'Map r, w and x to 4, 2 and 1 for each group.' }, { ar: 'راجع مبدأ أقل صلاحية قبل أي تعديل.', en: 'Review least privilege before changing permissions.' }], example: '-rw-r----- → 640', href: 'challenges.html?challenge=f-permissions' },
  { tag: 'INTEGRITY', title: { ar: 'بصمة SHA-256', en: 'SHA-256 fingerprint' }, purpose: { ar: 'قارن بصمة ملف تدريب بقيمة مرجعية كاملة للتحقق من سلامته.', en: 'Compare a training file fingerprint against a complete reference value to check integrity.' }, steps: [{ ar: 'احصل على البصمة المرجعية من مصدر موثوق.', en: 'Get the reference fingerprint from a trusted source.' }, { ar: 'احسب بصمة الملف المحلي.', en: 'Calculate the local file fingerprint.' }, { ar: 'قارن جميع الخانات؛ أي اختلاف يعني عدم التطابق.', en: 'Compare every character; any difference is a mismatch.' }], example: 'sha256sum training.txt', href: 'challenges.html?challenge=f-hash' },
  { tag: 'LOGS', title: { ar: 'قراءة السجلات', en: 'Read security logs' }, purpose: { ar: 'استخرج الوقت والمصدر والحدث، ثم اكتب استنتاجاً لا يتجاوز الدليل.', en: 'Extract time, source and event, then write a conclusion limited to the evidence.' }, steps: [{ ar: 'وحّد المنطقة الزمنية قبل ترتيب الأحداث.', en: 'Normalize the time zone before ordering events.' }, { ar: 'ابحث عن تكرار أو اختلاف في المصدر والحساب.', en: 'Look for patterns in sources and accounts.' }, { ar: 'دوّن ما لا يمكن إثباته من السجل وحده.', en: 'Record what the log alone cannot prove.' }], example: 'LOGIN_FAIL user=adam src=198.51.100.42', href: 'lab.html?id=log-triage' },
];

function frame(kicker, title, summary, count, body) {
  root.innerHTML = `<section class="catalog-hero section-frame"><a class="learning-back" href="paths.html">← ${tr('خطة التعلّم', 'Learning route')}</a><span class="section-kicker">${kicker}</span><h1>${title}</h1><p>${summary}</p>${count ? `<span class="catalog-count">${count}</span>` : ''}</section><section class="catalog-body section-frame">${body}</section>`;
}

function renderCourses() {
  const cards = courses.map((course, index) => `<article class="catalog-card"><div class="catalog-card-top"><span>COURSE / ${String(index + 1).padStart(2, '0')}</span><span class="catalog-live">${tr('متاح الآن', 'Available now')}</span></div><h2>${esc(l(course.title))}</h2><p>${esc(l(course.summary))}</p><div class="catalog-facts"><span>${course.minutes} ${tr('دقيقة', 'min')}</span><span>${course.lessonIds.length} ${tr('دروس', 'lessons')}</span></div><ol class="catalog-steps">${course.lessonIds.map((id) => `<li>${esc(l(lessonById[id].title))}</li>`).join('')}</ol><a class="button button-outline" href="course.html?id=${encodeURIComponent(course.id)}">${tr('افتح الكورس', 'Open course')} ↗</a></article>`).join('');
  frame('LEARN / COURSES', tr('الكورسات', 'Courses'), tr('ثلاثة كورسات في الأساسيات مرتبة: الروابط، الهوية والصلاحيات، ثم الأدلة والاستجابة. ابدأ من الخطوة الأولى وتابع بالترتيب.', 'Three ordered Foundations courses: URLs, identity and access, then evidence and response. Start at the first step and continue in order.'), `03 ${tr('كورسات أساسيات', 'Foundations courses')} · 19 ${tr('كورس برنامج', 'program courses')}`, `<div class="catalog-callout"><strong>${tr('من أين أبدأ؟', 'Where do I start?')}</strong><p>${tr('إذا كنت جديداً، ابدأ بكورس الروابط. بعد كل درس ستظهر لك الخطوة التالية.', 'If you are new, begin with URL safety. Each lesson points to your next step.')}</p><a href="course.html?id=url-safety">${tr('ابدأ الأساسيات', 'Start Foundations')} ↗</a></div><div class="catalog-grid">${cards}</div><div class="catalog-footer-note">${tr('بعد اجتياز امتحان الأساسيات، اقرأ كورسات تخصصك من مكتبة البرنامج. تُحفظ قراءة الدروس في حسابك، ثم تجتاز امتحان كل دورة والتقييم العملي ليفتح امتحان المسار وإثباته. XP والعملات الموثقة ترتبط حالياً بدروس الأساسيات.', 'After passing the Foundations exam, read your specialty courses in the program library. Lesson reading is saved to your account; each course exam and the path practical unlock its final exam and credential. Verified XP and coins currently come from Foundations lessons.')} <a href="paths.html#specializations">${tr('استكشف التخصصات', 'Explore specialties')} ↗</a></div>`);
}

function renderLabs() {
  const cards = labs.map((lab, index) => `<article class="catalog-card catalog-lab"><div class="catalog-card-top"><span>LAB / ${String(index + 1).padStart(2, '0')}</span><span class="catalog-live">${tr('متاح الآن', 'Available now')}</span></div><h2>${esc(l(lab.title))}</h2><p>${esc(l(lab.summary))}</p><div class="catalog-facts"><span>${lab.minutes} ${tr('دقيقة', 'min')}</span><span>${lab.steps.length} ${tr('خطوات', 'steps')}</span><span>${tr('عينة صناعية', 'Synthetic sample')}</span></div><p class="catalog-context">${tr('مرتبط بكورس:', 'Related course:')} <a href="course.html?id=${encodeURIComponent(lab.courseId)}">${esc(l(courses.find((course) => course.id === lab.courseId).title))}</a></p><a class="button button-outline" href="lab.html?id=${encodeURIComponent(lab.id)}">${tr('ابدأ المختبر', 'Start lab')} ↗</a></article>`).join('');
  frame('PRACTICE / LABS', tr('المختبرات العملية', 'Hands-on labs'), tr('طبّق ما تعلمته على أدلة صناعية آمنة. كل مختبر يوجّهك خطوة بخطوة ويشرح سبب الإجابة.', 'Apply what you learned to safe synthetic evidence. Each lab guides you step by step and explains the reasoning.'), `02 ${tr('مختبران موجّهان', 'guided labs')}`, `<div class="catalog-callout"><strong>${tr('متى أدخل المختبر؟', 'When should I take a lab?')}</strong><p>${tr('ابدأ بالكورس المرتبط به، ثم استخدم المختبر لتطبيق الفكرة. المختبرات تدريبية ولا تمنح XP موثقاً حالياً.', 'Start with its related course, then use the lab to apply the idea. Labs are practice and do not currently award verified XP.')}</p></div><div class="catalog-grid catalog-grid-two">${cards}</div>`);
}

function renderQuizzes() {
  const groups = courses.map((course, index) => `<section class="quiz-group"><div class="quiz-group-head"><span>COURSE / ${String(index + 1).padStart(2, '0')}</span><h2>${esc(l(course.title))}</h2></div><ol>${course.lessonIds.map((id, lessonIndex) => { const lesson = lessonById[id]; return `<li><span>${String(lessonIndex + 1).padStart(2, '0')}</span><div><strong>${esc(l(lesson.title))}</strong><small>${esc(l(lesson.check.question))}</small></div><a href="lesson.html?id=${encodeURIComponent(id)}#lesson-check">${tr('افتح تحقق الفهم', 'Open knowledge check')} ↗</a></li>`; }).join('')}</ol></section>`).join('');
  frame('PRACTICE / QUIZZES', tr('الاختبارات التدريبية', 'Practice quizzes'), tr('اختبر فهمك بعد الدروس ثم تدرب على أسئلة إضافية من البرنامج. امتحانات إكمال الدورات منفصلة وتفتح من صفحة كل دورة بعد قراءة دروسها.', 'Check your understanding after lessons, then practice with extra program questions. Graded course completion exams are separate and open from each course after its lessons.'), `09 ${tr('تحققات دروس', 'lesson checks')} · 13 ${tr('اختباراً تدريبياً', 'practice quizzes')}`, `<div class="catalog-callout"><strong>${tr('التدريب والامتحان مساران مختلفان', 'Practice and exams are separate')}</strong><p>${tr('أسئلة هذه الصفحة للمراجعة. امتحان إكمال الدورة يُصحح ويُحفظ في حسابك من صفحة الدورة، ولا تظهر أسئلته هنا.', 'Questions on this page are for review. A course completion exam is graded and saved to your account from its course page; its questions are not shown here.')}</p></div><div class="quiz-groups">${groups}</div><div class="catalog-final"><span>GRADED / COURSE EXAMS</span><h2>${tr('امتحانات الدورات في صفحاتها', 'Course exams live with their courses')}</h2><p>${tr('اقرأ دروس الدورة أولاً، ثم افتح امتحانها من صفحة الدورة. الاختبارات التدريبية هنا لا تمنح شهادة.', 'Read the course lessons first, then open its exam from the course page. These practice quizzes do not award a credential.')}</p><a class="button button-primary" href="courses.html">${tr('عرض الدورات', 'View courses')} ↗</a></div>`);
}

function renderTools() {
  const cards = toolGuides.map((guide) => `<details class="tool-guide"><summary><span>${guide.tag}</span><strong>${esc(l(guide.title))}</strong><i aria-hidden="true">+</i></summary><div class="tool-guide-body"><p>${esc(l(guide.purpose))}</p><ol>${guide.steps.map((step) => `<li>${esc(l(step))}</li>`).join('')}</ol><code dir="ltr">${esc(guide.example)}</code><a href="${guide.href}">${tr('جرّب تطبيقاً مرتبطاً', 'Try related practice')} ↗</a></div></details>`).join('');
  frame('REFERENCE / TOOLS', tr('دليل الأدوات', 'Tool guides'), tr('شروحات صغيرة تشرح وظيفة الأداة، كيف تقرأ مخرجاتها، ومتى تستخدمها في تدريب آمن. ابدأ بالأداة المرتبطة بدرسك.', 'Short guides explain each tool, how to read its output, and when to use it in safe practice. Start with the tool related to your lesson.'), `04 ${tr('أدلة أساسية', 'starter guides')}`, `<div class="catalog-callout"><strong>${tr('الأداة تساعدك على الفهم', 'Tools support your reasoning')}</strong><p>${tr('اقرأ الدليل أولاً، ثم طبق على عينة تدريبية. لا تفحص أنظمة أو بيانات لا تملك تصريحاً لاستخدامها.', 'Read the guide first, then practice on a training sample. Only inspect systems and data you are authorized to use.')}</p></div><div class="tool-guide-list">${cards}</div><div class="catalog-footer-note">${tr('تجد أدناه شروحات أدوات البرنامج الأصلية، بما فيها Nmap وWireshark وBurp Suite.', 'Original program guides, including Nmap, Wireshark and Burp Suite, appear below.')}</div>`);
}

function renderShop() {
  const items = [
    { icon: '◇', title: tr('تلميحات للتحديات', 'Challenge hints'), description: tr('مساعدة إضافية داخل التحديات عندما تحتاج دفعة صغيرة دون كشف الحل مباشرة.', 'Extra help inside challenges when you need a nudge without revealing the full answer.') },
    { icon: '▤', title: tr('ملاحظات تعليمية متقدمة', 'Advanced learning notes'), description: tr('مراجع مركزة وشروحات أعمق مرتبطة بالكورسات والمسارات.', 'Focused references and deeper explanations linked to courses and paths.') },
    { icon: '↘', title: tr('خصومات تعليمية مخططة', 'Planned learning discounts'), description: tr('اقترحنا سابقاً 200 عملة مقابل خصم 1$ على الاشتراك. بعد الانتقال لشراء المسارات، شروط الخصم لم تُعتمد بعد؛ لا يوجد تحويل أو استرداد نشط.', 'An earlier proposal was 200 coins for $1 off a subscription. Following the move to path purchases, discount terms have not been approved; conversion and redemption are inactive.') },
  ];
  frame('BIURET COINS / SHOP', tr('متجر الأكاديمية', 'Academy shop'), tr('مكان واضح لاستخدام عملات Biuret داخل الأكاديمية. نعرض هنا المزايا المخططة؛ الشراء والصرف غير مفعّلين بعد.', 'A clear place for using Biuret Coins inside the Academy. These benefits are planned; purchases and redemption are not active yet.'), '', `<div class="catalog-callout shop-notice"><strong>${tr('المتجر قيد الإعداد', 'Shop in development')}</strong><p>${tr('لا يوجد خصم أو شراء قابل للتنفيذ الآن. العملات السابقة محفوظة، وكسب العملات الجديدة متاح لعضويتي Plus وPro فقط.', 'No purchase or discount can be applied yet. Existing coins remain saved, and new coins can be earned only with Plus or Pro.')}</p><a href="progress.html">${tr('شاهد رصيدك وسجل العملات', 'View balance and coin history')} ↗</a></div><div class="shop-grid">${items.map((item) => `<article class="shop-item"><span class="shop-icon" aria-hidden="true">${item.icon}</span><span class="catalog-soon">${tr('مخطط', 'Planned')}</span><h2>${item.title}</h2><p>${item.description}</p></article>`).join('')}</div><div class="catalog-footer-note">${tr('عملات Biuret ليست نقوداً ولا يمكن سحبها أو استخدامها خارج الأكاديمية.', 'Biuret Coins are not cash and cannot be withdrawn or used outside the Academy.')} <a href="membership.html">${tr('الوصول والمشتريات', 'Access and purchases')} ↗</a></div>`);
}

function render() {
  if (!root) return;
  ({ courses: renderCourses, labs: renderLabs, quizzes: renderQuizzes, tools: renderTools, shop: renderShop })[page]?.();
}

document.querySelector('#language-toggle')?.addEventListener('click', render);
render();
