export const englishTracks = {
  foundations: { name: 'Foundations', summary: 'Read the everyday signals: links, Linux permissions, file hashes, and the web.', level: 'Beginner' },
  web: { name: 'Web security', summary: 'Understand requests and sessions, then separate authentication from authorization.', level: 'Beginner → Intermediate' },
  forensics: { name: 'Digital forensics', summary: 'Turn a short log or file fingerprint into a conclusion you can explain.', level: 'Beginner → Intermediate' },
};

export const englishChallenges = {
  'f-domain': {
    title: 'Read the URL', subtitle: 'Find the real host before you click', difficulty: 'Beginner',
    scenario: 'A message pretends to lead to a sign-in page. Identify the actual hostname in the displayed URL without opening it.',
    artifactLabel: 'URL to inspect', question: 'What is the hostname in this URL?', placeholder: 'Enter only the hostname',
    hint: 'The hostname is between // and the next /. Read the whole value, including its ending.',
    explanation: 'The hostname is login.biuret.dev.example.net. It ends in example.net; seeing biuret.dev earlier does not make it a Biuret domain.',
    takeaway: 'Check the actual domain ending, not familiar-looking words near the beginning.',
  },
  'f-permissions': {
    title: 'File permissions', subtitle: 'Translate Linux permissions into digits', difficulty: 'Beginner',
    scenario: 'A training file should allow its owner to read and write, its group to read, and everyone else no access.',
    artifactLabel: 'ls -l output', question: 'What is the numeric representation of these permissions?', placeholder: 'Example: 640',
    hint: 'r = 4, w = 2, and x = 1. Add the values separately for owner, group, and others.',
    explanation: 'The owner has rw- = 6, the group has r-- = 4, and others have --- = 0. The result is 640.',
    takeaway: 'File permissions express who can read, change, or execute a file.',
  },
  'f-hash': {
    title: 'File fingerprint', subtitle: 'Check a downloaded copy', difficulty: 'Beginner',
    scenario: 'A training organization published a reference SHA-256 fingerprint. Compare it with the downloaded copies.',
    artifactLabel: 'Shortened fingerprints for this exercise', artifact: 'Reference: 4f9c...a81d\nCopy A:    4f9c...a81d\nCopy B:    4f9c...a91d',
    question: 'Which copy matches the reference?', options: ['Copy A', 'Copy B', 'Both'],
    hint: 'Even one different character means the fingerprints do not match.',
    explanation: 'Copy A matches. Copy B differs near the end and cannot establish that it is the same file.',
    takeaway: 'Compare complete fingerprints; these shortened values are only for teaching.',
  },
  'f-redirect': {
    title: 'Response language', subtitle: 'Understand what the server says', difficulty: 'Beginner',
    scenario: 'After a request to a training server, the browser tools show this response.',
    artifactLabel: 'HTTP response', question: 'What does the server ask the browser to do?',
    options: ['Go to the sign-in page', 'Show a permanent server error', 'Cache the page forever'],
    hint: '302 means redirect. Location gives the destination.',
    explanation: '302 is a temporary redirect, and Location: /sign-in specifies where to go next.',
    takeaway: 'Read the status code and headers together to understand web behavior.',
  },
  'w-method': {
    title: 'Request intent', subtitle: 'Tell reading from changing state', difficulty: 'Beginner',
    scenario: 'A training interface needs to read a profile without changing its data.',
    artifactLabel: 'Two endpoints', question: 'Which request is normally appropriate for reading?',
    options: ['GET /profile', 'POST /profile', 'Both guarantee a change'],
    hint: 'Think about the intended meaning of GET in HTTP.',
    explanation: 'GET normally retrieves a resource. POST sends data that may create or change state.',
    takeaway: 'An HTTP method signals intent, but the server must enforce actual protection.',
  },
  'w-cookie': {
    title: 'A session behind the scenes', subtitle: 'Limit script access to the session', difficulty: 'Beginner',
    scenario: 'You are reviewing a training app cookie that contains a session identifier.',
    artifactLabel: 'Set-Cookie', question: 'Which attribute prevents page JavaScript from reading the session value directly?',
    options: ['HttpOnly', 'Max-Age=0', 'Path=/'],
    hint: 'Its name ties access to HTTP, away from document.cookie.',
    explanation: 'HttpOnly prevents JavaScript from reading the cookie directly. Secure and SameSite matter for other reasons.',
    takeaway: 'Session protection has several layers; one cookie attribute is never the whole solution.',
  },
  'w-output': {
    title: 'Show text safely', subtitle: 'Choose the right DOM property for user content', difficulty: 'Intermediate',
    scenario: 'You want to display a user-provided nickname as plain text, without interpreting it as HTML.',
    artifactLabel: 'Interface snippet', question: 'Which property belongs in the blank?',
    options: ['textContent', 'innerHTML', 'outerHTML'],
    hint: 'Choose the property that treats the value as text, not markup.',
    explanation: 'textContent displays plain text. innerHTML may interpret untrusted markup and create a security risk.',
    takeaway: 'Keep user text separate from HTML interpretation.',
  },
  'w-authorize': {
    title: 'Who owns the resource?', subtitle: 'Separate sign-in from permission checks', difficulty: 'Intermediate',
    scenario: 'A signed-in user requests a report owned by someone else. The server knows who made the request but has not checked ownership.',
    artifactLabel: 'Server-side decision', question: 'What check is missing before returning the report?',
    options: ['Check authorization for this report', 'Reload the page', 'Change the sign-in button color'],
    hint: 'Knowing who someone is does not permit them to read every resource.',
    explanation: 'Authentication confirms identity; authorization checks access to a specific resource. This request must be denied.',
    takeaway: 'Check access to each resource on the server.',
  },
  'd-log': {
    title: 'Read the log', subtitle: 'Find the source that stands out', difficulty: 'Beginner',
    scenario: 'These are synthetic training logs. Find the source IP with repeated failed sign-ins.',
    artifactLabel: 'auth.log — synthetic sample', question: 'Enter the IP address with repeated failures.', placeholder: 'Example: 192.0.2.1',
    hint: 'Find LOGIN_FAIL, then compare the source address on each line.',
    explanation: '198.51.100.42 appears in three close failed attempts. It deserves investigation, but does not prove an attack by itself.',
    takeaway: 'Forensics begins with a pattern, then gathers context before reaching a conclusion.',
  },
  'd-timeline': {
    title: 'A small timeline', subtitle: 'Order events by actual time', difficulty: 'Beginner',
    scenario: 'Find the first event in a training service log after converting all times to UTC.',
    artifactLabel: 'Logged events', question: 'Which event happened first?', options: ['A', 'B', 'C'],
    hint: 'Subtract three hours from UTC+3 times before comparing.',
    explanation: 'A is 07:40 UTC, B is 08:10 UTC, and C is 07:55 UTC. A happened first.',
    takeaway: 'Normalize time zones before ordering evidence.',
  },
  'd-integrity': {
    title: 'Evidence integrity', subtitle: 'Why record a file fingerprint?', difficulty: 'Intermediate',
    scenario: 'You copied a log file for analysis and want to check later that the copy did not change.',
    artifactLabel: 'Chain-of-custody record', question: 'What is the best step when opening the analysis copy?',
    options: ['Recompute and compare SHA-256', 'Only rename the file', 'Delete the old fingerprint'],
    hint: 'A change to the file contents will usually change its fingerprint.',
    explanation: 'Recomputing and comparing the fingerprint with the recorded value helps show that the contents stayed the same.',
    takeaway: 'Evidence integrity depends on repeatable recording and comparison.',
  },
  'd-triage': {
    title: 'Response decision', subtitle: 'Choose a responsible first step', difficulty: 'Intermediate',
    scenario: 'A training team spots many failed sign-ins on a test account. The information is still limited.',
    artifactLabel: 'Incident ticket — simulation', question: 'Which first step gathers evidence and preserves context?',
    options: ['Record time, source, and scope, then verify', 'Delete all logs immediately', 'Declare a confirmed breach before checking'],
    hint: 'Begin with a reviewable step that does not destroy evidence.',
    explanation: 'Documenting the signal and its context lets the team verify it and respond appropriately. Failed attempts alone do not prove a breach.',
    takeaway: 'Respond carefully, preserve evidence, and distinguish a signal from a conclusion.',
  },
};
