export const tracks = [
  {
    id: 'foundations', number: '01', icon: '⌘', name: 'الأساسيات', english: 'FOUNDATIONS',
    summary: 'افهم الإشارات التي تراها كل يوم: الروابط، لينكس، التجزئة، وحركة الويب.',
    tone: 'lime', level: 'مبتدئ',
  },
  {
    id: 'web', number: '02', icon: '◇', name: 'أمان الويب', english: 'WEB SECURITY',
    summary: 'اقرأ الطلبات والجلسات، وافصل بين التحقق من الهوية والصلاحيات.',
    tone: 'cyan', level: 'مبتدئ ← متوسط',
  },
  {
    id: 'forensics', number: '03', icon: '◉', name: 'الأدلة الرقمية', english: 'DIGITAL FORENSICS',
    summary: 'حوّل سجلاً صغيراً أو بصمة ملف إلى استنتاج يمكن الدفاع عنه.',
    tone: 'violet', level: 'مبتدئ ← متوسط',
  },
];

export const challenges = [
  {
    id: 'f-domain', track: 'foundations', order: 1, title: 'اقرأ الرابط جيداً',
    subtitle: 'تعرّف على النطاق الحقيقي قبل أن تضغط', difficulty: 'مبتدئ', minutes: 4, xp: 80, kind: 'text',
    scenario: 'وصلتك رسالة تتظاهر بأنها صفحة دخول. مهمتك تحديد اسم المضيف الحقيقي من الرابط المعروض، دون فتحه.',
    artifactLabel: 'رابط للتدقيق', artifact: 'https://login.biuret.dev.example.net/account/verify',
    question: 'ما اسم المضيف (hostname) في هذا الرابط؟', answers: ['login.biuret.dev.example.net'],
    placeholder: 'اكتب اسم المضيف فقط', hint: 'اسم المضيف هو الجزء الواقع بين // وأول / تالٍ له. اقرأه كاملاً من اليمين إلى اليسار.',
    explanation: 'المضيف هو login.biuret.dev.example.net، وينتهي بـ example.net. وجود biuret.dev في بدايته لا يجعل الرابط تابعاً لنطاق Biuret.',
    takeaway: 'افحص نهاية النطاق الحقيقية، وليس الكلمات التي تشبه اسم الموقع في بدايته.',
  },
  {
    id: 'f-permissions', track: 'foundations', order: 2, title: 'أذونات الملف',
    subtitle: 'ترجم حروف لينكس إلى صلاحيات رقمية', difficulty: 'مبتدئ', minutes: 5, xp: 90, kind: 'text',
    scenario: 'لديك ملف ملاحظات في بيئة تدريبية. تريد قراءة وكتابة للمالك، قراءة للمجموعة، ولا صلاحية للآخرين.',
    artifactLabel: 'ناتج ls -l', artifact: '-rw-r-----  1 learner analysts  814 Sep 26 notes.txt',
    question: 'ما التمثيل الرقمي لهذه الأذونات؟', answers: ['640'], placeholder: 'مثال: 640',
    hint: 'r = 4 و w = 2 و x = 1. اجمع صلاحيات كل مجموعة على حدة: المالك، المجموعة، الآخرون.',
    explanation: 'للمالك rw- = 6، للمجموعة r-- = 4، وللآخرين --- = 0. النتيجة 640.',
    takeaway: 'أذونات الملفات تصف من يستطيع القراءة أو التعديل أو التنفيذ.',
  },
  {
    id: 'f-hash', track: 'foundations', order: 3, title: 'بصمة الملف',
    subtitle: 'تحقق من سلامة نسخة محمّلة', difficulty: 'مبتدئ', minutes: 4, xp: 90, kind: 'choice',
    scenario: 'نشرت جهة تدريبية بصمة SHA-256 مرجعية لملف. قارنت بصمتها بما يظهر لديك بعد التنزيل.',
    artifactLabel: 'بصمات مصغّرة للتمرين', artifact: 'المرجع: 4f9c...a81d\nالنسخة A: 4f9c...a81d\nالنسخة B: 4f9c...a91d',
    question: 'أي نسخة تطابق البصمة المرجعية؟', options: ['النسخة A', 'النسخة B', 'كلتاهما'], answer: 'النسخة A',
    hint: 'حتى اختلاف خانة واحدة يعني أن البصمة ليست مطابقة.',
    explanation: 'النسخة A هي المطابقة. البصمة B تختلف في خانة قرب النهاية، لذلك لا تثبت سلامة الملف نفسه.',
    takeaway: 'المقارنة يجب أن تكون كاملة؛ القيم هنا مختصرة للعرض التعليمي فقط.',
  },
  {
    id: 'f-redirect', track: 'foundations', order: 4, title: 'لغة الاستجابة',
    subtitle: 'افهم ما يخبرك به الخادم', difficulty: 'مبتدئ', minutes: 4, xp: 100, kind: 'choice',
    scenario: 'بعد إرسال طلب إلى خادم تدريبي، ظهرت الاستجابة التالية في أدوات المتصفح.',
    artifactLabel: 'HTTP response', artifact: 'HTTP/1.1 302 Found\nLocation: /sign-in\nCache-Control: no-store',
    question: 'ما الذي يطلبه الخادم من المتصفح؟', options: ['الانتقال إلى صفحة تسجيل الدخول', 'عرض خطأ خادم دائم', 'حفظ الصفحة للأبد'], answer: 'الانتقال إلى صفحة تسجيل الدخول',
    hint: 'رمز 302 يدل على إعادة توجيه، وLocation يحدد الوجهة.',
    explanation: '302 استجابة إعادة توجيه مؤقتة، وLocation: /sign-in تحدد الصفحة التالية.',
    takeaway: 'اقرأ رمز الحالة والترويسات معاً لفهم سلوك الويب.',
  },
  {
    id: 'w-method', track: 'web', order: 1, title: 'نية الطلب',
    subtitle: 'ميّز بين القراءة وتغيير الحالة', difficulty: 'مبتدئ', minutes: 4, xp: 80, kind: 'choice',
    scenario: 'واجهة تدريبية تعرض ملفاً شخصياً، وتحتاج إلى طلب يقرأ البيانات من دون تعديلها.',
    artifactLabel: 'نقطتا نهاية', artifact: 'GET  /profile\nPOST /profile',
    question: 'أي طلب مناسب للقراءة المعتادة؟', options: ['GET /profile', 'POST /profile', 'كلاهما يضمن التعديل'], answer: 'GET /profile',
    hint: 'فكّر في معنى GET ضمن أساليب HTTP.',
    explanation: 'GET يُستخدم عادة لاسترجاع مورد. POST يُستخدم لإرسال بيانات قد تُنشئ أو تغيّر حالة.',
    takeaway: 'طريقة HTTP تشير إلى الغرض المتوقع، لكن الحماية الفعلية يفرضها الخادم.',
  },
  {
    id: 'w-cookie', track: 'web', order: 2, title: 'جلسة خلف الستار',
    subtitle: 'اختر السمة التي تقلل وصول السكربت للجلسة', difficulty: 'مبتدئ', minutes: 5, xp: 90, kind: 'choice',
    scenario: 'تراجع إعدادات ملف تعريف ارتباط يحمل معرف جلسة في تطبيق تدريبي.',
    artifactLabel: 'Set-Cookie', artifact: 'Set-Cookie: session=••••; Secure; SameSite=Lax; Path=/',
    question: 'أي سمة تضيفها لمنع JavaScript في الصفحة من قراءة قيمة الجلسة مباشرة؟', options: ['HttpOnly', 'Max-Age=0', 'Path=/'], answer: 'HttpOnly',
    hint: 'اسم السمة يربط الوصول بالبروتوكول HTTP، بعيداً عن document.cookie.',
    explanation: 'HttpOnly تمنع JavaScript من قراءة ملف تعريف الارتباط مباشرة. Secure وSameSite مهمتان أيضاً لأسباب مختلفة.',
    takeaway: 'حماية الجلسة طبقات متعددة، ولا تكفي سمة واحدة وحدها.',
  },
  {
    id: 'w-output', track: 'web', order: 3, title: 'اعرض النص بأمان',
    subtitle: 'اختر واجهة DOM المناسبة لمحتوى المستخدم', difficulty: 'متوسط', minutes: 6, xp: 110, kind: 'choice',
    scenario: 'تريد عرض لقب كتبه المستخدم داخل عنصر في الصفحة كنص عادي، من دون تفسيره كـ HTML.',
    artifactLabel: 'جزء من الواجهة', artifact: 'const nickname = userInput;\nprofileName.____ = nickname;',
    question: 'أي خاصية تضع مكان الفراغ؟', options: ['textContent', 'innerHTML', 'outerHTML'], answer: 'textContent',
    hint: 'اختر الخاصية التي تعامل القيمة كنص، لا كوسوم.',
    explanation: 'textContent تعرض القيمة كنص. استخدام innerHTML مع مدخل غير موثوق قد يفسّر الوسوم ويخلق خطراً أمنياً.',
    takeaway: 'عند عرض مدخلات المستخدم، افصل النص عن تفسير HTML.',
  },
  {
    id: 'w-authorize', track: 'web', order: 4, title: 'من يملك المورد؟',
    subtitle: 'فرّق بين تسجيل الدخول والتحقق من الصلاحية', difficulty: 'متوسط', minutes: 6, xp: 120, kind: 'choice',
    scenario: 'مستخدم مسجل الدخول يطلب فتح تقرير يخص مستخدماً آخر. الخادم يعرف هوية الطالب، لكنه لم يتحقق من ملكية التقرير.',
    artifactLabel: 'قرار على الخادم', artifact: 'request.userId = "user_A"\nreport.ownerId = "user_B"',
    question: 'ما الفحص الناقص قبل إرجاع التقرير؟', options: ['التحقق من تفويض المستخدم لهذا التقرير', 'إعادة تحميل الصفحة', 'تغيير لون زر الدخول'], answer: 'التحقق من تفويض المستخدم لهذا التقرير',
    hint: 'معرفة من هو المستخدم لا تعني السماح له بقراءة كل مورد.',
    explanation: 'المصادقة تؤكد الهوية، أما التفويض فيتحقق من حق المستخدم في المورد المحدد. يجب رفض الطلب هنا.',
    takeaway: 'تحقق من صلاحية الوصول لكل مورد على الخادم.',
  },
  {
    id: 'd-log', track: 'forensics', order: 1, title: 'اقرأ السجل',
    subtitle: 'حدد المصدر الأكثر إثارة للانتباه', difficulty: 'مبتدئ', minutes: 5, xp: 80, kind: 'text',
    scenario: 'هذه عينة سجلات تدريبية. ابحث عن عنوان المصدر الذي تكرر معه فشل تسجيل الدخول.',
    artifactLabel: 'auth.log — عينة صناعية', artifact: '09:11:02  192.0.2.14   LOGIN_OK\n09:12:18  198.51.100.42 LOGIN_FAIL\n09:12:21  198.51.100.42 LOGIN_FAIL\n09:12:24  198.51.100.42 LOGIN_FAIL\n09:15:09  203.0.113.7  LOGIN_OK',
    question: 'اكتب عنوان IP صاحب المحاولات الفاشلة المتكررة.', answers: ['198.51.100.42'], placeholder: 'مثال: 192.0.2.1',
    hint: 'ابحث عن LOGIN_FAIL، ثم قارن عنوان المصدر في كل سطر.',
    explanation: 'العنوان 198.51.100.42 ظهر في ثلاث محاولات فاشلة متقاربة. هذه إشارة للتحقيق، وليست دليلاً قاطعاً على هجوم.',
    takeaway: 'الأدلة الرقمية تبدأ بملاحظة نمط، ثم جمع سياق قبل إصدار حكم.',
  },
  {
    id: 'd-timeline', track: 'forensics', order: 2, title: 'خط زمني صغير',
    subtitle: 'رتّب الأحداث حسب الوقت الفعلي', difficulty: 'مبتدئ', minutes: 5, xp: 90, kind: 'choice',
    scenario: 'تحتاج إلى تحديد أول حدث من سجلات خدمة اختبار بعد توحيد المنطقة الزمنية إلى UTC.',
    artifactLabel: 'أحداث مسجلة', artifact: 'A  10:40 UTC+3\nB  08:10 UTC+0\nC  10:55 UTC+3',
    question: 'أي حدث وقع أولاً؟', options: ['A', 'B', 'C'], answer: 'A',
    hint: 'اطرح ثلاث ساعات من أوقات UTC+3 ثم قارن.',
    explanation: 'A يساوي 07:40 UTC، وB يساوي 08:10 UTC، وC يساوي 07:55 UTC؛ لذلك A هو الأسبق.',
    takeaway: 'وحّد المناطق الزمنية قبل ترتيب الأدلة.',
  },
  {
    id: 'd-integrity', track: 'forensics', order: 3, title: 'سلامة الدليل',
    subtitle: 'افهم لماذا نوثّق بصمة العينة', difficulty: 'متوسط', minutes: 5, xp: 100, kind: 'choice',
    scenario: 'نسخت ملف سجل لأغراض التحليل. تريد التحقق لاحقاً أن النسخة لم تتغير أثناء العمل.',
    artifactLabel: 'سجل سلسلة الحيازة', artifact: 'evidence: incident-log.txt\nsha256: 59d2…c43a\ncollected_at: 2026-09-26T08:00:00Z',
    question: 'ما الإجراء الأفضل عند فتح النسخة للتحليل؟', options: ['إعادة حساب SHA-256 ومقارنتها', 'تغيير اسم الملف فقط', 'حذف البصمة القديمة'], answer: 'إعادة حساب SHA-256 ومقارنتها',
    hint: 'أي تغيير في محتوى الملف يغيّر بصمته عادة.',
    explanation: 'إعادة حساب البصمة ومقارنتها بالقيمة الموثقة تساعد على إثبات أن المحتوى لم يتغير.',
    takeaway: 'سلامة الدليل تتطلب توثيقاً ومقارنة قابلة للتكرار.',
  },
  {
    id: 'd-triage', track: 'forensics', order: 4, title: 'قرار الاستجابة',
    subtitle: 'اختر أول خطوة مسؤولة بعد رصد إشارة', difficulty: 'متوسط', minutes: 6, xp: 120, kind: 'choice',
    scenario: 'رصد فريق تدريبي عدداً مرتفعاً من محاولات الدخول الفاشلة على حساب اختبار. المعلومات لا تزال محدودة.',
    artifactLabel: 'تذكرة حادثة — محاكاة', artifact: 'signal: repeated failed sign-ins\nasset: test account\nconfidence: low\nimpact: unknown',
    question: 'أي خطوة أولى تجمع دليلاً وتحافظ على السياق؟', options: ['توثيق التوقيت والمصدر ونطاق الأثر ثم التحقق', 'حذف كل السجلات فوراً', 'إعلان اختراق مؤكد قبل التحقق'], answer: 'توثيق التوقيت والمصدر ونطاق الأثر ثم التحقق',
    hint: 'ابدأ بخطوة قابلة للمراجعة ولا تدمّر الأدلة.',
    explanation: 'توثيق الإشارة وجمع سياقها يمكّن الفريق من التحقق والاحتواء المناسب لاحقاً. المحاولات الفاشلة وحدها لا تثبت اختراقاً.',
    takeaway: 'استجب بحذر، واحفظ الدليل، وميّز بين الإشارة والاستنتاج.',
  },
  {
    id: 'f-sender', track: 'foundations', order: 5, title: 'اسم مرسل أم دليل؟',
    subtitle: 'افصل الاسم الظاهر عن عنوان البريد', difficulty: 'مبتدئ', minutes: 5, xp: 100, kind: 'text',
    scenario: 'وصلتك رسالة تدريبية بعنوان «فريق الدعم» تطلب تحديث كلمة المرور. افحص عنوان المرسل قبل أي تفاعل.',
    artifactLabel: 'رأس رسالة صناعية', artifact: 'From: "Biuret Support" <help@biuret.example.net>\nReply-To: reset@other.example.net\nSubject: Verify your account',
    question: 'ما النطاق الموجود بعد @ في عنوان From؟', answers: ['biuret.example.net'], placeholder: 'اكتب النطاق فقط',
    hint: 'تجاهل الاسم بين علامتي الاقتباس. اقرأ ما يأتي بعد @ داخل الأقواس الزاوية.',
    explanation: 'عنوان From ينتهي بـ biuret.example.net؛ الاسم الظاهر «Biuret Support» لا يثبت هوية الجهة. اختلاف Reply-To إشارة إضافية للفحص.',
    takeaway: 'تحقق من العنوان الفعلي وتواصل مع الجهة عبر قناة معروفة، ولا تعتمد على اسم العرض وحده.',
  },
  {
    id: 'w-private-cache', track: 'web', order: 5, title: 'استجابة شخصية في الذاكرة المؤقتة',
    subtitle: 'راجع ترويسة التخزين لبيانات حساب', difficulty: 'متوسط', minutes: 6, xp: 110, kind: 'choice',
    scenario: 'تعرض خدمة تدريبية بيانات حساب شخصي. راجع ترويسة التخزين قبل أن تسمح للوسائط المشتركة بحفظ الاستجابة.',
    artifactLabel: 'HTTP response — محاكاة', artifact: 'GET /account/profile\nHTTP/1.1 200 OK\nCache-Control: public, max-age=3600\nContent-Type: application/json\n{ "email": "student@example.net" }',
    question: 'أي تغيير يناسب استجابة شخصية حساسة؟', options: ['Cache-Control: private, no-store', 'زيادة max-age إلى يوم كامل', 'حذف Content-Type فقط'], answer: 'Cache-Control: private, no-store',
    hint: 'فكر في الفرق بين تخزين عام لعدة مستخدمين واستجابة يجب ألا تُحفظ.',
    explanation: 'public يسمح بتخزين الاستجابة في مخابئ مشتركة؛ private, no-store يمنع حفظ هذا المحتوى الحساس. القرار النهائي يعتمد على طبيعة البيانات.',
    takeaway: 'سياسات التخزين المؤقت جزء من حماية البيانات، إضافة إلى المصادقة والتفويض.',
  },
  {
    id: 'd-correlation', track: 'forensics', order: 5, title: 'اربط الأحداث بحذر',
    subtitle: 'لا تنسب حدثين لبعضهما دون دليل', difficulty: 'متوسط', minutes: 6, xp: 110, kind: 'choice',
    scenario: 'لاحظ المحلل فشل دخول متكرر لحساب ثم دخولاً ناجحاً لحساب آخر من عنوان مختلف. يحتاج ملخصاً لا يتجاوز ما تثبته السجلات.',
    artifactLabel: 'سجل تدريب صناعي', artifact: '10:00  LOGIN_FAIL user=adam src=198.51.100.42\n10:01  LOGIN_FAIL user=adam src=198.51.100.42\n10:04  LOGIN_OK   user=sara src=203.0.113.7',
    question: 'أي وصف دقيق لهذه العينة وحدها؟', options: ['فشلان لحساب adam ودخول ناجح مختلف لحساب sara', 'نجح المهاجم في دخول حساب adam', 'دخول sara يثبت أن المصدرين شخص واحد'], answer: 'فشلان لحساب adam ودخول ناجح مختلف لحساب sara',
    hint: 'قارن اسم الحساب وعنوان المصدر في كل حدث، ثم افصل الملاحظة عن الفرضية.',
    explanation: 'لا يوجد LOGIN_OK لحساب adam، كما أن المصدر والحساب مختلفان في الحدث الثالث. الربط بينهما يحتاج سياقاً إضافياً.',
    takeaway: 'التقارب الزمني وحده لا يثبت علاقة سببية بين أحداث مختلفة.',
  },
];

export const challengeById = Object.fromEntries(challenges.map((challenge) => [challenge.id, challenge]));
export const challengesForTrack = (trackId) => challenges.filter((challenge) => challenge.track === trackId).sort((a, b) => a.order - b.order);
