export const pageContexts = {
  home: ['HOME', 'رحلة التعلّم تبدأ هنا.', 'Your learning journey starts here.'],
  paths: ['PATHS', 'طريقك من الأساسيات إلى التخصص.', 'Your route from foundations to a specialty.'],
  courses: ['COURSES', 'كورسات مرتبة تبني معرفتك.', 'Courses that build your knowledge in order.'],
  course: ['COURSE', 'تعلّم موضوعاً واحداً خطوة بخطوة.', 'Learn one topic, step by step.'],
  lesson: ['LESSON', 'ركّز على خطوتك التالية.', 'Focus on your next learning step.'],
  labs: ['LABS', 'طبّق ما تعلّمته بأمان.', 'Practice what you learned safely.'],
  lab: ['LAB', 'مختبر عملي موجّه وآمن.', 'A safe, guided hands-on lab.'],
  quizzes: ['QUIZZES', 'اختبر فهمك بعد كل خطوة.', 'Check your understanding after each step.'],
  challenges: ['CHALLENGES', 'تحديات قصيرة تثبّت مهاراتك.', 'Short challenges to strengthen your skills.'],
  tools: ['TOOLS', 'تعرّف إلى الأدوات وطريقة استخدامها.', 'Explore tools and how to use them.'],
  progress: ['PROGRESS', 'تابع ما أنجزته والخطوة القادمة.', 'Track what you completed and what comes next.'],
  exam: ['EXAM', 'اختبر أساسياتك بعد إكمال الدروس.', 'Test your foundations after the lessons.'],
  'path-exam': ['PATH EXAM', 'امتحان تخصصك وإثبات إنجازه.', 'Your specialty exam and credential.'],
  'course-exam': ['COURSE EXAM', 'امتحان دورتك ونتيجته.', 'Your course exam and result.'],
  practical: ['PRACTICAL', 'طبّق ما تعلمته على أدلة تدريبية.', 'Apply your learning to training evidence.'],
  certificate: ['CREDENTIAL', 'اعرض إثبات إنجازك وتحقّق منه.', 'View and verify your achievement.'],
  membership: ['MEMBERSHIP', 'اختر مزايا التعلّم المناسبة لك.', 'Explore the learning benefits that fit you.'],
  shop: ['SHOP', 'استكشف مزايا عملات Biuret.', 'Explore Biuret Coins benefits.'],
  admin: ['ADMIN', 'إدارة إثباتات الإنجاز.', 'Manage achievement credentials.'],
  review: ['REVIEW', 'راجع دروسك بانتظام.', 'Review your lessons regularly.'],
  operations: ['OPERATIONS', 'حلل حوادث واقعية بمحاكاة آمنة.', 'Investigate incidents in safe simulations.'],
  operation: ['OPERATION', 'اتخذ قراراً مبنياً على الدليل.', 'Make an evidence-based decision.'],
  certifications: ['CERTIFICATIONS', 'استكشف مسارات الشهادات المهنية.', 'Explore professional certification paths.'],
  professional: ['PROFESSIONAL HUB', 'حوّل تعلمك إلى مهارات عملية.', 'Turn learning into practical skills.'],
  notes: ['NOTES', 'اجمع أفكارك أثناء التعلّم.', 'Keep your learning notes together.'],
  favorites: ['FAVORITES', 'ارجع سريعاً إلى ما حفظته.', 'Return to what you saved.'],
  search: ['SEARCH', 'ابحث في محتوى الأكاديمية.', 'Search Academy content.'],
  settings: ['SETTINGS', 'اضبط تجربة تعلّمك.', 'Adjust your learning experience.'],
  profile: ['PROFILE', 'حسابك ومسار تقدّمك.', 'Your account and learning route.'],
  'library-course': ['COURSE LIBRARY', 'دروس الكورس في مكان واحد.', 'All course lessons in one place.'],
  'library-lesson': ['LESSON LIBRARY', 'اقرأ الدرس ودوّن ما تعلّمته.', 'Read and capture what you learned.'],
  'practice-quiz': ['PRACTICE QUIZ', 'اختبار تدريبي من برنامج الأكاديمية.', 'A practice quiz from the Academy program.'],
  'practice-lab': ['PRACTICE LAB', 'حلل عينة مختبر صناعية.', 'Analyze a synthetic lab sample.'],
  'practice-challenge': ['PRACTICE CHALLENGE', 'حل تحدياً إضافياً بالتفكير.', 'Solve another reasoning challenge.'],
};

export function pageContext(page) {
  const [label, arabic, english] = pageContexts[page];
  return `<div class="page-header-context"><span>ACADEMY / ${label}</span><strong data-ar="${arabic}" data-en="${english}">${arabic}</strong></div>`;
}
